"""HTML report renderer for benchmark results — self-contained, no external deps."""

from __future__ import annotations

from pathlib import Path

from agentra.models import BenchmarkReport, SkillBenchmark

_CSS = """
:root {
  --bg: #0d1117; --surface: #161b22; --border: #30363d;
  --text: #e6edf3; --text-dim: #8b949e; --accent: #58a6ff;
  --green: #3fb950; --red: #f85149; --yellow: #d29922; --blue: #58a6ff;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
       background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 1200px; margin: 0 auto; }
h1 { font-size: 2rem; margin-bottom: .5rem; }
h2 { font-size: 1.4rem; margin: 2rem 0 1rem; border-bottom: 1px solid var(--border); padding-bottom: .5rem; }
h3 { font-size: 1.15rem; margin: 1.5rem 0 .5rem; }
.meta { color: var(--text-dim); margin-bottom: 2rem; }
.card { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; }
.badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: .8rem; font-weight: 600; }
.badge-pass { background: rgba(63,185,80,.15); color: var(--green); }
.badge-fail { background: rgba(248,81,73,.15); color: var(--red); }
.badge-sev-critical { background: rgba(248,81,73,.15); color: var(--red); }
.badge-sev-high { background: rgba(210,153,34,.15); color: var(--yellow); }
.badge-sev-medium { background: rgba(88,166,255,.15); color: var(--blue); }
.badge-sev-low { background: rgba(139,148,158,.15); color: var(--text-dim); }
table { width: 100%; border-collapse: collapse; margin: .75rem 0; }
th { text-align: left; padding: .6rem .75rem; background: var(--surface); border-bottom: 2px solid var(--border); font-size: .85rem; color: var(--text-dim); text-transform: uppercase; letter-spacing: .05em; }
td { padding: .5rem .75rem; border-bottom: 1px solid var(--border); font-size: .9rem; }
tr:hover td { background: rgba(88,166,255,.04); }
.metric-bar { height: 8px; border-radius: 4px; background: var(--border); position: relative; overflow: hidden; }
.metric-bar-fill { height: 100%; border-radius: 4px; background: linear-gradient(90deg, var(--green), var(--accent)); transition: width .6s ease; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0; }
.stat { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }
.stat-value { font-size: 2rem; font-weight: 700; color: var(--accent); }
.stat-label { font-size: .85rem; color: var(--text-dim); margin-top: .25rem; }
.footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--text-dim); font-size: .8rem; text-align: center; }
"""  # noqa: E501


class HtmlRenderer:
    """Renders benchmark report as a self-contained HTML document."""

    def render(self, report: BenchmarkReport, output_path: Path) -> None:
        html = self._build(report)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")

    def render_string(self, report: BenchmarkReport) -> str:
        return self._build(report)

    def _build(self, report: BenchmarkReport) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agentra — Benchmark Report</title>
<style>{_CSS}</style>
</head>
<body>

<h1>Agentra — Benchmark Report</h1>
<p class="meta">Project: <strong>{_esc(report.project_name)}</strong> &middot; Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</p>

{self._stats_section(report)}
{self._stack_section(report)}
{self._governance_section(report)}
{self._optimization_section(report)}
{self._skills_section(report)}

<div class="footer">Generated by Agentra — Enterprise AI Engineering Control Plane</div>
</body>
</html>"""  # noqa: E501

    # ── Stats cards ──────────────────────────────────────────────────────

    def _stats_section(self, r: BenchmarkReport) -> str:
        total_skills = len(r.skill_benchmarks)
        verified = sum(1 for s in r.skill_benchmarks if s.verification_passed)
        total_metrics = sum(len(s.metrics) for s in r.skill_benchmarks)
        avg_improvement = 0.0
        all_improvements = [m.improvement_pct for s in r.skill_benchmarks for m in s.metrics if m.improvement_pct > 0]
        if all_improvements:
            avg_improvement = sum(all_improvements) / len(all_improvements)

        return f"""
<div class="stats">
  <div class="stat"><div class="stat-value">{total_skills}</div><div class="stat-label">Skills Evaluated</div></div>
  <div class="stat"><div class="stat-value">{verified}/{total_skills}</div><div class="stat-label">Verified</div></div>
  <div class="stat"><div class="stat-value">{total_metrics}</div><div class="stat-label">Metrics Measured</div></div>
  <div class="stat"><div class="stat-value">{avg_improvement:.1f}%</div><div class="stat-label">Avg Improvement</div></div>
  <div class="stat"><div class="stat-value">{r.optimization.reduction_pct:.1f}%</div><div class="stat-label">Token Reduction</div></div>
  <div class="stat"><div class="stat-value">{len(r.governance.violations)}</div><div class="stat-label">Violations Found</div></div>
</div>"""  # noqa: E501

    # ── Stack ────────────────────────────────────────────────────────────

    def _stack_section(self, r: BenchmarkReport) -> str:
        rows = ""
        for cat, label in [
            ("languages", "Languages"), ("frameworks", "Frameworks"),
            ("databases", "Databases"), ("sdks", "SDKs"),
            ("infrastructure", "Infrastructure"), ("cloud_providers", "Cloud"),
            ("ci_cd", "CI/CD"), ("agents", "Agents"),
        ]:
            components = getattr(r.stack, cat)
            if components:
                names = ", ".join(
                    f'{_esc(c.name)} <span class="badge badge-pass">{c.confidence:.0%}</span>'
                    for c in components
                )
                rows += f"<tr><td><strong>{label}</strong></td><td>{names}</td></tr>\n"

        return f"""
<h2>Detected Stack</h2>
<table><thead><tr><th>Category</th><th>Components</th></tr></thead>
<tbody>{rows}</tbody></table>"""

    # ── Governance ───────────────────────────────────────────────────────

    def _governance_section(self, r: BenchmarkReport) -> str:
        status_badge = '<span class="badge badge-pass">PASSED</span>' if r.governance.passed else '<span class="badge badge-fail">FAILED</span>'  # noqa: E501

        violation_rows = ""
        for v in r.governance.violations[:30]:
            sev_class = f"badge-sev-{v.rule.severity.value}"
            violation_rows += (
                f'<tr><td>{_esc(v.rule.id)}</td>'
                f'<td><span class="badge {sev_class}">{v.rule.severity.value}</span></td>'
                f'<td>{_esc(v.rule.category.value)}</td>'
                f'<td>{_esc(v.rule.name)}</td>'
                f'<td>{_esc(str(v.file_path or "N/A")[-40:])}</td></tr>\n'
            )

        violations_table = ""
        if r.governance.violations:
            violations_table = f"""
<table><thead><tr><th>ID</th><th>Severity</th><th>Category</th><th>Rule</th><th>File</th></tr></thead>
<tbody>{violation_rows}</tbody></table>"""

        return f"""
<h2>Governance Summary</h2>
<div class="card">
  <p>{status_badge} &middot; <strong>{len(r.governance.violations)}</strong> violations &middot;
  Risk Score: <strong>{r.governance.risk_score:.1f}</strong> &middot;
  Blast Radius: <strong>{r.governance.blast_radius}</strong></p>
</div>
{violations_table}"""

    # ── Optimization ─────────────────────────────────────────────────────

    def _optimization_section(self, r: BenchmarkReport) -> str:
        pct = min(r.optimization.reduction_pct, 100)
        return f"""
<h2>Token Optimization</h2>
<div class="card">
  <p>Original: <strong>{r.optimization.original_tokens}</strong> tokens →
  Optimized: <strong>{r.optimization.optimized_tokens}</strong> tokens
  (<strong>{r.optimization.reduction_pct:.1f}%</strong> reduction)</p>
  <div class="metric-bar"><div class="metric-bar-fill" style="width: {pct}%"></div></div>
  <p style="margin-top:.5rem;color:var(--text-dim);">
    Rules included: {r.optimization.rules_included} &middot; Excluded: {r.optimization.rules_excluded}
  </p>
</div>"""

    # ── Skills ───────────────────────────────────────────────────────────

    def _skills_section(self, r: BenchmarkReport) -> str:
        sections: list[str] = ["<h2>Skill Benchmarks</h2>"]
        for sb in r.skill_benchmarks:
            sections.append(self._skill_card(sb))
        return "\n".join(sections)

    def _skill_card(self, sb: SkillBenchmark) -> str:
        badge = '<span class="badge badge-pass">VERIFIED</span>' if sb.verification_passed else '<span class="badge badge-fail">UNVERIFIED</span>'  # noqa: E501

        metric_rows = ""
        for m in sb.metrics:
            before_fmt = f"{m.before:.1f}" if isinstance(m.before, float) and m.before != int(m.before) else str(int(m.before))  # noqa: E501
            after_fmt = f"{m.after:.1f}" if isinstance(m.after, float) and m.after != int(m.after) else str(int(m.after))  # noqa: E501
            bar_pct = min(m.improvement_pct, 100)
            metric_rows += f"""<tr>
  <td>{_esc(m.name)}</td>
  <td>{before_fmt}</td><td>{after_fmt}</td><td>{_esc(m.unit)}</td>
  <td><div class="metric-bar" style="width:120px;display:inline-block;vertical-align:middle">
    <div class="metric-bar-fill" style="width:{bar_pct}%"></div>
  </div> {m.improvement_pct:.1f}%</td>
  <td style="color:var(--text-dim)">{_esc(m.description[:80])}</td>
</tr>\n"""

        return f"""
<div class="card">
  <h3>{_esc(sb.skill_name)} {badge}</h3>
  <p style="color:var(--text-dim);margin:.25rem 0"><code>{sb.skill_id}</code> &middot; {_esc(sb.verification_details[:120])}</p>
  <table>
    <thead><tr><th>Metric</th><th>Before</th><th>After</th><th>Unit</th><th>Improvement</th><th>Description</th></tr></thead>
    <tbody>{metric_rows}</tbody>
  </table>
</div>"""  # noqa: E501


def _esc(text: str) -> str:
    """Minimal HTML escaping."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
