"""Markdown report renderer for benchmark results."""

from __future__ import annotations

from pathlib import Path

from agentra.models import BenchmarkReport


class MarkdownRenderer:
    """Renders benchmark report as a Markdown document."""

    def render(self, report: BenchmarkReport, output_path: Path) -> None:
        lines = self._build(report)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines), encoding="utf-8")

    def render_string(self, report: BenchmarkReport) -> str:
        return "\n".join(self._build(report))

    def _build(self, report: BenchmarkReport) -> list[str]:
        lines: list[str] = []

        # Header
        lines.append("# Agentra — Benchmark Report")
        lines.append("")
        lines.append(f"**Project:** {report.project_name}")
        lines.append(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append("")

        # Stack summary
        lines.append("## Detected Stack")
        lines.append("")
        lines.append("| Category | Components |")
        lines.append("|----------|-----------|")
        for cat, label in [
            ("languages", "Languages"),
            ("frameworks", "Frameworks"),
            ("databases", "Databases"),
            ("sdks", "SDKs"),
            ("infrastructure", "Infrastructure"),
            ("cloud_providers", "Cloud"),
            ("ci_cd", "CI/CD"),
            ("agents", "Agents"),
        ]:
            components = getattr(report.stack, cat)
            if components:
                names = ", ".join(f"{c.name} ({c.confidence:.0%})" for c in components)
                lines.append(f"| {label} | {names} |")
        lines.append("")

        # Governance summary
        lines.append("## Governance Summary")
        lines.append("")
        status = "✅ PASSED" if report.governance.passed else "❌ FAILED"
        lines.append(f"- **Status:** {status}")
        lines.append(f"- **Violations:** {len(report.governance.violations)}")
        lines.append(f"- **Risk Score:** {report.governance.risk_score:.1f}")
        lines.append(f"- **Blast Radius:** {report.governance.blast_radius}")
        lines.append("")

        if report.governance.violations:
            lines.append("### Violations")
            lines.append("")
            lines.append("| ID | Severity | Category | Rule | File |")
            lines.append("|----|----------|----------|------|------|")
            for v in report.governance.violations[:30]:
                lines.append(
                    f"| {v.rule.id} | {v.rule.severity.value} | {v.rule.category.value} "
                    f"| {v.rule.name} | {v.file_path or 'N/A'} |"
                )
            lines.append("")

        # Optimization summary
        lines.append("## Token Optimization")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Original tokens | {report.optimization.original_tokens} |")
        lines.append(f"| Optimized tokens | {report.optimization.optimized_tokens} |")
        lines.append(f"| Reduction | {report.optimization.reduction_pct:.1f}% |")
        lines.append(f"| Rules included | {report.optimization.rules_included} |")
        lines.append(f"| Rules excluded | {report.optimization.rules_excluded} |")
        lines.append("")

        # Skill benchmarks
        lines.append("## Skill Benchmarks")
        lines.append("")

        for sb in report.skill_benchmarks:
            verified = "✅" if sb.verification_passed else "❌"
            lines.append(f"### {sb.skill_name} {verified}")
            lines.append("")
            lines.append(f"- **ID:** `{sb.skill_id}`")
            lines.append(f"- **Verified:** {sb.verification_details}")
            lines.append("")

            if sb.metrics:
                lines.append("| Metric | Before | After | Unit | Improvement |")
                lines.append("|--------|--------|-------|------|-------------|")
                for m in sb.metrics:
                    before_fmt = f"{m.before:.1f}" if isinstance(m.before, float) and m.before != int(m.before) else str(int(m.before))  # noqa: E501
                    after_fmt = f"{m.after:.1f}" if isinstance(m.after, float) and m.after != int(m.after) else str(int(m.after))  # noqa: E501
                    lines.append(
                        f"| {m.name} | {before_fmt} | {after_fmt} "
                        f"| {m.unit} | {m.improvement_pct:.1f}% |"
                    )
                lines.append("")

            if sb.metrics:
                lines.append(f"_{self._summary_for_skill(sb)}_")
                lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by Agentra — Enterprise AI Engineering Control Plane*")

        return lines

    def _summary_for_skill(self, sb) -> str:
        """Generate a one-line summary for a skill benchmark."""
        best = max(sb.metrics, key=lambda m: m.improvement_pct, default=None)
        if best and best.improvement_pct > 0:
            return f"Best improvement: {best.name} — {best.improvement_pct:.1f}% gain."
        return "Skill active with baseline metrics."
